api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "line-update-addon-interaction"
type = "function"
uid = "2a99fbfc-5c98-1de7-f7fc-ad71798f2103882dbdf3"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
